name: Build Minimal cvlc

# 1. Trigger daily at midnight UTC (adjust cron as needed)
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

jobs:
  build-cvlc:
    runs-on: ubuntu-latest
    steps:
      # 2. Check out repository (if you have patches or scripts here)
      - name: Checkout repo
        uses: actions/checkout@v4

      # 3. Install build dependencies
      - name: Set up build dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libavformat-dev \
          libswscale-dev \
          libavfilter-dev \
          libavresample-dev
          libopus-dev \
          libvorbis-dev \
          libtheora-dev \
          libvpx-dev \
          liba52-0.7.4-dev \
          libmad0-dev \
          libogg-dev \
          libflac-dev \
          git \
          build-essential \
          pkg-config \
          autoconf \
          automake \
          libtool \
          autopoint \
          gettext

      # 4. Clone VLC source
      - name: Clone VLC
        run: |
          git clone --depth=1 https://code.videolan.org/videolan/vlc.git
          cd vlc

      # 5. Bootstrap & configure minimal build
      - name: Configure headless cvlc
        working-directory: vlc
        run: |
          ./bootstrap
          ./configure \
            --disable-gui \
            --disable-skins2 \
            --disable-xcb \
            --disable-qt \
            --disable-lua \
            --disable-mad \
            --disable-dbus \
            --disable-sdl \
            --disable-jack \
            --disable-a52 \
            --disable-mjpeg \
            --disable-microdns \
            --enable-libopus \
            --enable-libvorbis \
            --prefix="$PWD/build"

      # 6. Build only cvlc
      - name: Build cvlc
        working-directory: vlc
        run: |
          make -C vlc/cvlc -j$(nproc)
          make install -C vlc/cvlc

      # 7. Package the result
      - name: Package minimal cvlc
        run: |
          cd vlc/build
          tar czf ../minimal-cvlc-$(date +%Y%m%d).tar.gz bin/cvlc lib/libvlc* plugins/

      # 8. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minimal-cvlc
          path: vlc/minimal-cvlc-*.tar.gz
