name: Build Minimal CVLC for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            git
            autoconf
            automake
            libtool
            make

      - name: Install VLC build dependencies
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S \
            mingw-w64-x86_64-liblua \
            mingw-w64-x86_64-pulse \
            mingw-w64-x86_64-ffmpeg

      - name: Build minimal CVLC
        shell: msys2 {0}
        run: |
          set -e

          # 1. Clone VLC source
          git clone --depth 1 https://code.videolan.org/videolan/vlc.git
          cd vlc

          # 2. Bootstrap & configure audio-only + HTTP/socket
          ./bootstrap
          ./configure \
            --host=x86_64-w64-mingw32 \
            --disable-video \
            --disable-skins2 \
            --disable-lua \
            --disable-x11 \
            --disable-dbus \
            --disable-sdl \
            --disable-chromaprint \
            --disable-mad \
            --disable-flac \
            --disable-theora \
            --enable-decoder=mp3,opus,vorbis \
            --enable-avcodec \
            --enable-avformat \
            --enable-swresample \
            --enable-pulse \
            --enable-sout \
            --enable-http \
            --enable-socket \
            --prefix="$PWD/../inst"

          # 3. Compile & install
          make -j "$(nproc)"
          make install

          # 4. Package binary tree
          cd ..
          7z a cvlc-windows.zip inst/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cvlc-windows
          path: cvlc-windows.zip
